version: '3'
services:
    config-service:
        container_name: config-service
        build: ./config-service
        ports:
            -   8088:8088
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8088/discovery-service/default"]
            interval: 30s
            timeout: 10s
            retries: 5

    discovery-service:
        container_name: discovery-service
        build: ./discovery-service
        restart: on-failure
        ports:
            -   8061:8061
        depends_on:
            - config-service

    auth-service:
        container_name: auth-service
        build: ./auth-service
        restart: on-failure
        ports: 
            -   8081:8081
        depends_on:
            -   config-service

    admin-service:
        container_name: admin-service
        build: ./admin-service
        restart: on-failure
        ports:
            - 8095:8095
        depends_on:
            - config-service
            - gateway-service
            - discovery-service

    gateway-service:
        container_name: gateway-service
        build: ./gateway-service
        restart: on-failure
        ports: 
            -   8060:8060
        depends_on:
            -   config-service
    cart-service:
        container_name: cart-service
        build: ./cart-service
        restart: on-failure
        ports: 
            -   8092:8092
        depends_on:
            -   config-service
    orders-service:
        container_name: orders-service
        build: ./orders-service
        restart: on-failure
        ports: 
            -   8091:8091
        depends_on:
            -   config-service
    product-service:
        container_name: product-service
        build: ./product-service
        restart: on-failure
        ports: 
            -   8090:8090
        depends_on:
            -   config-service
    stock-service:
        container_name: stock-service
        build: ./stock-service
        restart: on-failure
        ports: 
            -   8094:8094
        depends_on:
            -   config-service
    user-service:
        container_name: user-service
        build: ./user-service
        restart: on-failure
        ports: 
            -   8093:8093
        depends_on:
            -   config-service
